### ISSUE TITLE
TFT Wiring

### ISSUE THREAD

**Issue by wisnusatriyo** [ESPboy-edu/ESPboy_Sub1GHzInspector#4]
Hi All,
I am making this project but I am stuck with the wiring TFT 1.44 Display to Node MCU. Thanks in advance for someone can share the wiring info.  I am from Indonesia

**Comment by ESPboy-edu** [comment]
[Please check here ](https://www.instructables.com/ESPboy-DIY-Retro-Gaming-and-Software-Development-M/) and welcome to [ESPboy project Discord chat](https://discord.gg/Jbq9rCEYvy)

**Comment by wisnusatriyo** [comment]
Thanks for the reply much appreciated, however the wiring is for ESPboy DIY - Retro Gaming and Software Development Multi-tool instead of  [ESPboy_Sub1GHzInspector] . Do you have for this specific wiring?

**Comment by ESPboy-edu** [comment]
Sub1GHzInspector is extention module for ESPboy + specific software.
So you have to assemble ESPboy first, then assemble Sub1GHzInspector extention module, then connect Sub1GHzInspector module to ESPboy and finaly upload Sub1GHzInspector software to ESPboy

**Comment by wisnusatriyo** [comment]
OK Thanks I got from TFT Library.  Connections are as follows: (TFT vs NodeMCU
BL/LED  to 5V
SCL/SCK to D5
MOSI/SDA to D7
DC/A0 to D3
RST to D0
CS to GND
GND to GND
VCC to VCC

**Comment by ESPboy-edu** [comment]
Why are you asking for advice but not following it? ;)
Check the TFT connection diagramm[ here](https://www.instructables.com/ESPboy-DIY-Retro-Gaming-and-Software-Development-M/) if you want my project to work as intended.

**Comment by wisnusatriyo** [comment]
Noted and much appreciated for the advice.
