### ISSUE TITLE
Project cannot be compiled

### ISSUE THREAD

**Issue by JohnPheby** [ESPboy-edu/ESPboy_Sub1GHzInspector#6]
The ESPboy_Sub1GHzInspector project cannot be compiled in ArduinoIDE, the Adafruit_MCP23017 library does not match,
new #include <Adafruit_MCP23X17.h> //GPIO extender (buttons and more)
mcp.begin(MCP23017address); 'class Adafruit_MCP23X17' has no member named 'begin' change to begin_I2C
mcp.pullUp(i, HIGH); 'class Adafruit_MCP23X17' has no member named 'pullUp' also fails if you comment it out.
uint8_t ESPboyInit::getKeys() { return (~mcp.readGPIOAB() & 255); } qualified-id in declaration before '(' token
ESPboy FIRST TEST - Adafruit libs does not compile similarly.
void loop(){ a function-definition is not allowed here before '{' token

**Comment by ESPboy-edu** [comment]
Hi.
Please use recommended Arduino IDE libs to work with the ESPboy
https://github.com/ESPboy-edu/ESPboy_ArduinoIDE_Libraries
